### ISSUE TITLE
Question about the 'func_defs' key of the JSON file of HPCorpus_sub dataset

### ISSUE THREAD

**Issue by Mority5** [Scientific-Computing-Lab-NRCN/MonoCoder#1]

**Comment by Mority5** [comment]
Hello,

I have been exploring the data in your repository and encountered a question regarding the '/data/HPCorpus_sub/c_sub.jsonl' JSON file. I am particularly curious about the 'func_defs' key. Could you please explain waht the information under 'func_defs' represents?

I would also like to understand why this information is included in the dataset and what its intended purpose is. Any clarification you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by talkad** [comment]
Hello there,

Each sample in the dataset is a function extracted from a code file in a relevant repository (C/C++ codes). After extracting each function, we also include all the function definitions (only the signatures) from the same file and the included headers. This ensures that the code's compatibility can be checked for future use cases.

**Comment by Mority5** [comment]
@talkad Thank you for the detailed response! I get it.
